2022-06-14 04:47:07,419:DEBUG:certbot._internal.main:certbot version: 1.28.0
2022-06-14 04:47:07,420:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2022-06-14 04:47:07,420:DEBUG:certbot._internal.main:Arguments: ['--webroot', '-w', '/var/www/certbot', '--email', 'yatongzhao0622@gmail.com', '-d', 'zbook.top', '--rsa-key-size', '4096', '--agree-tos', '--force-renewal']
2022-06-14 04:47:07,420:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-06-14 04:47:07,433:DEBUG:certbot._internal.log:Root logging level set at 30
2022-06-14 04:47:07,434:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2022-06-14 04:47:07,437:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fc88f011550>
Prep: True
2022-06-14 04:47:07,437:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fc88f011550> and installer None
2022-06-14 04:47:07,437:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2022-06-14 04:47:07,461:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/587561376', new_authzr_uri=None, terms_of_service=None), 6077b00bc68df4204aadede5e19c8257, Meta(creation_dt=datetime.datetime(2022, 6, 14, 4, 30, 44, tzinfo=<UTC>), creation_host='fa815168dfda', register_to_eff='yatongzhao0622@gmail.com'))>
2022-06-14 04:47:07,462:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2022-06-14 04:47:07,463:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2022-06-14 04:47:08,227:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2022-06-14 04:47:08,227:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 14 Jun 2022 04:47:07 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "YZzQBqBchy8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2022-06-14 04:47:08,228:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for zbook.top
2022-06-14 04:47:08,772:DEBUG:certbot.crypto_util:Generating RSA key (4096 bits): /etc/letsencrypt/keys/0006_key-certbot.pem
2022-06-14 04:47:08,780:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0006_csr-certbot.pem
2022-06-14 04:47:08,781:DEBUG:acme.client:Requesting fresh nonce
2022-06-14 04:47:08,781:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2022-06-14 04:47:08,967:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2022-06-14 04:47:08,968:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 14 Jun 2022 04:47:08 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002zHJFskVdRBuvDW-hK6BGfhNTIaPDFig-BwuJNvIM24M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2022-06-14 04:47:08,968:DEBUG:acme.client:Storing nonce: 0002zHJFskVdRBuvDW-hK6BGfhNTIaPDFig-BwuJNvIM24M
2022-06-14 04:47:08,968:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "zbook.top"\n    }\n  ]\n}'
2022-06-14 04:47:08,974:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNTg3NTYxMzc2IiwgIm5vbmNlIjogIjAwMDJ6SEpGc2tWZFJCdXZEVy1oSzZCR2ZoTlRJYVBERmlnLUJ3dUpOdklNMjRNIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "Bw-GzyXJ0BWNVVrGEuqunBZWZFhhYQ86qyoXzfHU0HjweQuPFxVSh1j-H-oc778ilKreHPxcSKgpzNKrL5SPOCyqxfWdmIAbnio5BYAIlSzkusaOiIFznFNdI3uThULDMazStSTV2FbiDZNUHYelba5Z6la0QRNRuvCf_TTs8qv3esZAeG6K7fk3OUSr4Ttp54eJaoQlEgPCpZ9YkCHnkjqduo2sC7aRsITe5tuGMK-Xp1LiYt4-a7qhVSjWR21IJ5u0ZT0Mxd01vxhueu0UWw6nsEQT1eAyPVHeRowhShA-QQFICHclC7y3YtLKNdtxghzGOnO_zLwPg8NOenDy25u0f7V9FlMR2BHVIHQNDQqAO0rjEJRA4rSd-9rOMsKoVygmsz4_1NPq1-hXtCu7LYC1g50ecy5bKMAkB1DnwIi8UV1eX7RexpGFb0C9Bh1H1vZjp2KwI4enmwD2kKpYgBlaS06a6cCPaTwnggKfaREICCh_J6F7q6Th5CnRqUJgAXEdcGdPVGH7J5p35t5BXL-iNY7yr5Khs0siej1r-qLLuPB1sutqxxJ2YbtQJDwLZPzJ2ydHik3It56B5u-gTa1CbxVUa_bq_6s3L0GAr7eyKjATesRohxCELZu7XtDbY2e7RMS0clnuNe1WrhjOurDMaeDSbbaHH_Oq_bj9liY",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInpib29rLnRvcCIKICAgIH0KICBdCn0"
}
2022-06-14 04:47:09,213:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 201
2022-06-14 04:47:09,213:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Tue, 14 Jun 2022 04:47:09 GMT
Content-Type: application/problem+json
Content-Length: 201
Connection: keep-alive
Boulder-Requester: 587561376
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002UrW2gJbkO4i8GPpq0YS2SrneNeOMxhmlnzqPWnLsKqI

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
2022-06-14 04:47:09,214:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1591, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 513, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 441, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 475, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 943, in new_order
    return cast(ClientV2, self.client).new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 704, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 103, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1276, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 1290, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 1136, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
2022-06-14 04:47:09,215:ERROR:certbot._internal.log:An unexpected error occurred:
2022-06-14 04:47:09,215:ERROR:certbot._internal.log:Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
